name: 📋 Admission Scraper

on:
  workflow_dispatch:

jobs:
  scrape-and-commit:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install Chrome & dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable fonts-liberation \
                                  libappindicator3-1 xdg-utils

      - name: Install Python dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install selenium webdriver-manager

      - name: Run admission scraper
        run: python scrape_admissions.py

      - name: Commit & push admissions.json
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add admissions.json
          if ! git diff --cached --quiet; then
            git commit -m "ci: update admissions.json"
            git push
          else
            echo "No changes to commit"
          fi
