name: 🏫 College Scraper

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    timeout-minutes: 360 # ⏱️ prevent timeout-related cancel

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run scraper
        run: python overview.py

      # ✅ Upload as artifact for safe backup
      - name: Upload scraped data
        uses: actions/upload-artifact@v4
        with:
          name: college-overviews
          path: college_overviews.json

      # ✅ Git commit only if data changed
      - name: Commit & push results
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add college_overviews.json
          if ! git diff --cached --quiet; then
            git commit -m "ci: update college_overviews.json"
            git push
          else
            echo "No changes to commit"
          fi
